version: '3'
services:
  tv-server:
    build:
      context: ./back-tv
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    container_name: back-tv
    volumes:
      - ./back-tv:/usr/src/app/back-tv
  vue-ui:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
      - ./front:/usr/src/app/front
  api:
    build:
      context: ./back-api
      dockerfile: Dockerfile
    ports:
      - "3088:3088"
    container_name: back-api
    volumes:
      - ./back-api:/usr/src/app/back-api
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 6nGDVJsEr69A6Len
      MONGO_INITDB_DATABASE: tvvf
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro